# clk => 100000000Hz
create_clock -period 10.0 -name clk_0 -waveform {0.000 5.000} [get_ports clk]
set_property PACKAGE_PIN N14 [get_ports {clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {clk}]
set_property PACKAGE_PIN P6 [get_ports {rst_n}]
set_property IOSTANDARD LVCMOS33 [get_ports {rst_n}]

set_property PACKAGE_PIN K13        [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[0]}]
set_property PACKAGE_PIN K12        [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[1]}]
set_property PACKAGE_PIN L14        [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[2]}]
set_property PACKAGE_PIN L13        [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[3]}]
set_property PACKAGE_PIN M16        [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[4]}]
set_property PACKAGE_PIN M14        [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[5]}]
set_property PACKAGE_PIN M12        [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[6]}]
set_property PACKAGE_PIN N16        [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[7]}]

set_property PACKAGE_PIN T7 [get_ports {uart_tx}]
set_property IOSTANDARD LVCMOS33 [get_ports {uart_tx}]

set_property PACKAGE_PIN T8 [get_ports {uart_rx}]
set_property IOSTANDARD LVCMOS33 [get_ports {uart_rx}]

set_property PACKAGE_PIN C4         [get_ports {DAC_IN[0]}]
set_property IOSTANDARD LVCMOS33    [get_ports {DAC_IN[0]}]
set_property PACKAGE_PIN E3         [get_ports {DAC_IN[1]}]
set_property IOSTANDARD LVCMOS33    [get_ports {DAC_IN[1]}]
set_property PACKAGE_PIN D3         [get_ports {DAC_IN[2]}]
set_property IOSTANDARD LVCMOS33    [get_ports {DAC_IN[2]}]
set_property PACKAGE_PIN C3         [get_ports {DAC_IN[3]}]
set_property IOSTANDARD LVCMOS33    [get_ports {DAC_IN[3]}]
set_property PACKAGE_PIN C2         [get_ports {DAC_IN[4]}]
set_property IOSTANDARD LVCMOS33    [get_ports {DAC_IN[4]}]
set_property PACKAGE_PIN C1         [get_ports {DAC_IN[5]}]
set_property IOSTANDARD LVCMOS33    [get_ports {DAC_IN[5]}]
set_property PACKAGE_PIN B1         [get_ports {DAC_IN[6]}]
set_property IOSTANDARD LVCMOS33    [get_ports {DAC_IN[6]}]
set_property PACKAGE_PIN D1         [get_ports {DAC_IN[7]}]
set_property IOSTANDARD LVCMOS33    [get_ports {DAC_IN[7]}]
set_property PACKAGE_PIN E2         [get_ports {DAC_IN[8]}]
set_property IOSTANDARD LVCMOS33    [get_ports {DAC_IN[8]}]
set_property PACKAGE_PIN A2         [get_ports {DAC_IN[9]}]
set_property IOSTANDARD LVCMOS33    [get_ports {DAC_IN[9]}]
set_property PACKAGE_PIN E2         [get_ports {DAC_IN[10]}]
set_property IOSTANDARD LVCMOS33    [get_ports {DAC_IN[10]}]
set_property PACKAGE_PIN E1         [get_ports {DAC_IN[11]}]
set_property IOSTANDARD LVCMOS33    [get_ports {DAC_IN[11]}]
set_property PACKAGE_PIN F2         [get_ports {DAC_IN[12]}]
set_property IOSTANDARD LVCMOS33    [get_ports {DAC_IN[12]}]
set_property PACKAGE_PIN F3         [get_ports {DAC_IN[13]}]
set_property IOSTANDARD LVCMOS33    [get_ports {DAC_IN[13]}]